version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - ./docker-data/elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.4.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27019:27019
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DOKCER_MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DOKCER_MONGO_PASSWORD}
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DOKCER_MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DOKCER_MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  redis:
    image: 'redis:alpine'
    container_name: redis
    ports:
      - '5000:6379'

    volumes:
      - ./docker-data/redis-data:/data
